[package]
name = "kaprekar_numbers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayref = "0.3.7"
num = "0.4.3"
rayon = "1.8"
sortnet = "0.1.0"

[lints.rust]
unsafe_code = "forbid"
